/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as PokedexIndexRouteImport } from './routes/pokedex/index'
import { Route as LivingDexIndexRouteImport } from './routes/living-dex/index'
import { Route as BoxesIndexRouteImport } from './routes/boxes/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as PokedexSpeciesIdRouteImport } from './routes/pokedex/$speciesId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexIndexRoute = PokedexIndexRouteImport.update({
  id: '/pokedex/',
  path: '/pokedex/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivingDexIndexRoute = LivingDexIndexRouteImport.update({
  id: '/living-dex/',
  path: '/living-dex/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesIndexRoute = BoxesIndexRouteImport.update({
  id: '/boxes/',
  path: '/boxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexSpeciesIdRoute = PokedexSpeciesIdRouteImport.update({
  id: '/pokedex/$speciesId',
  path: '/pokedex/$speciesId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/pokedex/$speciesId': typeof PokedexSpeciesIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/boxes/': typeof BoxesIndexRoute
  '/living-dex/': typeof LivingDexIndexRoute
  '/pokedex/': typeof PokedexIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/pokedex/$speciesId': typeof PokedexSpeciesIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/boxes': typeof BoxesIndexRoute
  '/living-dex': typeof LivingDexIndexRoute
  '/pokedex': typeof PokedexIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/pokedex/$speciesId': typeof PokedexSpeciesIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/boxes/': typeof BoxesIndexRoute
  '/living-dex/': typeof LivingDexIndexRoute
  '/pokedex/': typeof PokedexIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/pokedex/$speciesId'
    | '/teams/$teamId'
    | '/boxes/'
    | '/living-dex/'
    | '/pokedex/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/pokedex/$speciesId'
    | '/teams/$teamId'
    | '/boxes'
    | '/living-dex'
    | '/pokedex'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/pokedex/$speciesId'
    | '/teams/$teamId'
    | '/boxes/'
    | '/living-dex/'
    | '/pokedex/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  PokedexSpeciesIdRoute: typeof PokedexSpeciesIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  BoxesIndexRoute: typeof BoxesIndexRoute
  LivingDexIndexRoute: typeof LivingDexIndexRoute
  PokedexIndexRoute: typeof PokedexIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex/': {
      id: '/pokedex/'
      path: '/pokedex'
      fullPath: '/pokedex/'
      preLoaderRoute: typeof PokedexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/living-dex/': {
      id: '/living-dex/'
      path: '/living-dex'
      fullPath: '/living-dex/'
      preLoaderRoute: typeof LivingDexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/': {
      id: '/boxes/'
      path: '/boxes'
      fullPath: '/boxes/'
      preLoaderRoute: typeof BoxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex/$speciesId': {
      id: '/pokedex/$speciesId'
      path: '/pokedex/$speciesId'
      fullPath: '/pokedex/$speciesId'
      preLoaderRoute: typeof PokedexSpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  PokedexSpeciesIdRoute: PokedexSpeciesIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  BoxesIndexRoute: BoxesIndexRoute,
  LivingDexIndexRoute: LivingDexIndexRoute,
  PokedexIndexRoute: PokedexIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
