/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppPokedexIndexRouteImport } from './routes/_app/pokedex/index'
import { Route as AppDexIndexRouteImport } from './routes/_app/dex/index'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app/teams/$teamId'
import { Route as AppPokedexSpeciesIdRouteImport } from './routes/_app/pokedex/$speciesId'
import { Route as AppDexDexIdRouteImport } from './routes/_app/dex/$dexId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppRoute,
} as any)
const AppPokedexIndexRoute = AppPokedexIndexRouteImport.update({
  id: '/pokedex/',
  path: '/pokedex/',
  getParentRoute: () => AppRoute,
} as any)
const AppDexIndexRoute = AppDexIndexRouteImport.update({
  id: '/dex/',
  path: '/dex/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppRoute,
} as any)
const AppPokedexSpeciesIdRoute = AppPokedexSpeciesIdRouteImport.update({
  id: '/pokedex/$speciesId',
  path: '/pokedex/$speciesId',
  getParentRoute: () => AppRoute,
} as any)
const AppDexDexIdRoute = AppDexDexIdRouteImport.update({
  id: '/dex/$dexId',
  path: '/dex/$dexId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dex/$dexId': typeof AppDexDexIdRoute
  '/pokedex/$speciesId': typeof AppPokedexSpeciesIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/dex/': typeof AppDexIndexRoute
  '/pokedex/': typeof AppPokedexIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/dex/$dexId': typeof AppDexDexIdRoute
  '/pokedex/$speciesId': typeof AppPokedexSpeciesIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/dex': typeof AppDexIndexRoute
  '/pokedex': typeof AppPokedexIndexRoute
  '/teams': typeof AppTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/dex/$dexId': typeof AppDexDexIdRoute
  '/_app/pokedex/$speciesId': typeof AppPokedexSpeciesIdRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/_app/dex/': typeof AppDexIndexRoute
  '/_app/pokedex/': typeof AppPokedexIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/dex/$dexId'
    | '/pokedex/$speciesId'
    | '/teams/$teamId'
    | '/dex/'
    | '/pokedex/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/'
    | '/dex/$dexId'
    | '/pokedex/$speciesId'
    | '/teams/$teamId'
    | '/dex'
    | '/pokedex'
    | '/teams'
  id:
    | '__root__'
    | '/_app'
    | '/auth/login'
    | '/_app/'
    | '/_app/dex/$dexId'
    | '/_app/pokedex/$speciesId'
    | '/_app/teams/$teamId'
    | '/_app/dex/'
    | '/_app/pokedex/'
    | '/_app/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pokedex/': {
      id: '/_app/pokedex/'
      path: '/pokedex'
      fullPath: '/pokedex/'
      preLoaderRoute: typeof AppPokedexIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dex/': {
      id: '/_app/dex/'
      path: '/dex'
      fullPath: '/dex/'
      preLoaderRoute: typeof AppDexIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pokedex/$speciesId': {
      id: '/_app/pokedex/$speciesId'
      path: '/pokedex/$speciesId'
      fullPath: '/pokedex/$speciesId'
      preLoaderRoute: typeof AppPokedexSpeciesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dex/$dexId': {
      id: '/_app/dex/$dexId'
      path: '/dex/$dexId'
      fullPath: '/dex/$dexId'
      preLoaderRoute: typeof AppDexDexIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDexDexIdRoute: typeof AppDexDexIdRoute
  AppPokedexSpeciesIdRoute: typeof AppPokedexSpeciesIdRoute
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
  AppDexIndexRoute: typeof AppDexIndexRoute
  AppPokedexIndexRoute: typeof AppPokedexIndexRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDexDexIdRoute: AppDexDexIdRoute,
  AppPokedexSpeciesIdRoute: AppPokedexSpeciesIdRoute,
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
  AppDexIndexRoute: AppDexIndexRoute,
  AppPokedexIndexRoute: AppPokedexIndexRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
